walkoverweb/viasocket-chatbot

src/pages/interface/components/Interface-Chatbot/Message.tsx

removed content overflow

---

src/api/InterfaceApis/InterfaceApis.ts
src/pages/interface/components/Interface-Chatbot/Message.tsx

Python server for  send message

Prod deployment

---

src/pages/interface/components/Interface-Chatbot/Message.tsx

showing error in chatbot and optimize message card as well

showing error in chatbot and optimize message card as well

---

src/pages/interface/components/Interface-Chatbot/Message.tsx

showing error in chatbot and optimize message card

showing error in chatbot and optimize message card

---

src/App.js
src/pages/interface/components/Chatbot-Wrapper/ChatbotWrapper.tsx
src/pages/interface/components/Interface-Chatbot/ChatbotHeader.tsx
src/pages/interface/components/Interface-Chatbot/InterfaceChatbot.tsx
src/pages/interface/pages/InterfaceEmbed/InterfaceEmbed.tsx

editable chatbot title and description

editable chatbot title and description

---

src/pages/interface/components/Interface-Button/InterfaceButton.tsx
src/pages/interface/utils/InterfaceUtils.ts

Send Data action

---

src/pages/interface/components/Interface-Button/InterfaceButton.tsx
src/pages/interface/utils/InterfaceUtils.ts

only one action for sending data to frontend

only one action for sending data to frontend

---

src/pages/interface/components/Interface-Chatbot/Message.tsx

handling for chatbot message & normal message

handling for chatbot message & normal message

---

src/pages/interface/components/Interface-Chatbot/Message.tsx

handling for chatbot and normal message

handling for chatbot and normal message

---

src/api/InterfaceApis/InterfaceApis.ts
src/pages/interface/components/Interface-Chatbot/ChatbotHeader.tsx
src/pages/interface/components/Interface-Chatbot/InterfaceChatbot.tsx
src/pages/interface/components/Interface-Chatbot/Message.tsx
src/pages/interface/components/Interface-Chatbot/MessageList.tsx

reset history

---

src/pages/interface/components/ComponentRenderer.tsx
src/pages/interface/components/Grid/Grid.tsx
src/pages/interface/components/Interface-Button/InterfaceButton.tsx
src/pages/interface/components/Interface-Card/InterfaceCard.tsx

mui card support- testing

---

src/pages/interface/components/Interface-Chatbot/MessageList.tsx

scroll to down icon  bug

---

src/pages/interface/components/Interface-Chatbot/MessageList.tsx

scroll down icon  bug

---

src/pages/interface/components/Interface-Chatbot/Message.tsx
src/pages/interface/components/Interface-Chatbot/MessageList.tsx

only calling apis when necessary

only calling apis when necessary

---

src/api/InterfaceApis/InterfaceApis.ts
src/pages/interface/components/Interface-Chatbot/InterfaceChatbot.tsx
src/pages/interface/components/Interface-Chatbot/Message.tsx
src/pages/interface/components/Interface-Chatbot/MessageList.tsx

feedback support main

---

src/pages/interface/components/Interface-Chatbot/ChatbotHeader.tsx

chatbot feedback support webhook = testing

chatbot feedback support webhook = testing

---

src/pages/interface/components/Interface-Chatbot/ChatbotHeader.tsx

Chatbot Feedback support main

---

src/pages/interface/components/Interface-Button/InterfaceButton.tsx
src/pages/interface/components/Interface-Chatbot/ChatbotTextField.tsx
src/pages/interface/components/Interface-Chatbot/InterfaceChatbot.scss
src/pages/interface/components/Interface-Chatbot/InterfaceChatbot.tsx
src/pages/interface/components/Interface-Chatbot/Message.tsx
src/pages/interface/components/Interface-Chatbot/MessageList.tsx
src/pages/interface/components/Interface-Chatbot/MoveToDownButton.tsx

showing next options in chatbot - testing

showing next options in chatbot - testing

---

src/pages/interface/components/Interface-Button/InterfaceButton.tsx
src/pages/interface/components/Interface-Chatbot/ChatbotTextField.tsx
src/pages/interface/components/Interface-Chatbot/InterfaceChatbot.scss
src/pages/interface/components/Interface-Chatbot/InterfaceChatbot.tsx
src/pages/interface/components/Interface-Chatbot/Message.tsx
src/pages/interface/components/Interface-Chatbot/MessageList.tsx
src/pages/interface/components/Interface-Chatbot/MoveToDownButton.tsx

showing next question suggestion main

showing next question suggestion main

---

src/pages/interface/components/Interface-Chatbot/InterfaceChatbot.tsx
src/pages/interface/components/Interface-Chatbot/Message.scss
src/pages/interface/components/Interface-Chatbot/Message.tsx

bridgename dependency added

---

src/pages/interface/components/Interface-Chatbot/Message.scss
src/pages/interface/components/Interface-Chatbot/Message.tsx

animation in chatbot message

---

src/pages/interface/components/Interface-Chatbot/Message.scss
src/pages/interface/components/Interface-Chatbot/Message.tsx

animation in chatbot message - main

animation in chatbot message - main

---

src/pages/interface/components/Interface-Chatbot/Interface-Markdown/CodeBlock.tsx
src/pages/interface/components/Interface-Chatbot/Interface-Markdown/MarkdownUtitily.tsx

lighter built for syntax highlighter

lighter built for syntax highlighter

---

src/interceptor/interceptor.js
src/pages/interface/components/Chatbot-Wrapper/ChatbotWrapper.tsx
src/pages/interface/components/Interface-Chatbot/ChatbotHeader.tsx
src/pages/interface/components/Interface-Chatbot/InterfaceChatbot.tsx
src/pages/interface/pages/InterfaceEmbed/InterfaceEmbed.tsx
src/pages/interface/utils/InterfaceUtils.ts
src/store/interface/interfaceReducer.ts

token issue and bridgename and threadid issue fix = testing
1. Store data in session storage

token issue and bridgename and threadid issue fix = testing

---

src/interceptor/interceptor.js
src/pages/interface/components/Chatbot-Wrapper/ChatbotWrapper.tsx
src/pages/interface/components/Interface-Chatbot/ChatbotHeader.tsx
src/pages/interface/components/Interface-Chatbot/InterfaceChatbot.tsx
src/pages/interface/pages/InterfaceEmbed/InterfaceEmbed.tsx
src/pages/interface/utils/InterfaceUtils.ts
src/store/interface/interfaceReducer.ts

token issue and bridgename and threadid issue fix-main
Storing bridgename, threadId and chatbot token and userid in session storage instead of local storage

token issue and bridgename and threadid issue fix-main

---

src/pages/interface/components/Interface-Chatbot/Message.scss
src/pages/interface/components/Interface-Chatbot/Message.tsx

loading style change- testing

---

src/pages/interface/components/Interface-Chatbot/Message.scss
src/pages/interface/components/Interface-Chatbot/Message.tsx

loading style change

---

package-lock.json
src/pages/interface/components/Interface-Chatbot/InterfaceChatbot.tsx
src/pages/interface/components/Interface-Chatbot/Message.tsx

image generation support

---

src/pages/interface/components/Interface-Chatbot/InterfaceChatbot.tsx
src/pages/interface/components/Interface-Chatbot/Message.tsx

image generation support main

---

src/pages/interface/components/Interface-Chatbot/ChatbotDrawer.tsx
src/pages/interface/components/Interface-Chatbot/InterfaceChatbot.tsx
src/store/interface/interfaceReducer.ts

subthread save in redux instead of session storage

subthread save in redux instead of session storage

---

src/pages/interface/components/Interface-Chatbot/InterfaceChatbot.tsx

remove console

---

src/pages/interface/components/Interface-Chatbot/Message.tsx

updated preview images for vision

updated preview images for vision

---

src/pages/interface/components/Interface-Chatbot/ChatbotDrawer.tsx

turncate the sub thread id main

turncate the sub thread id main

---

src/pages/interface/components/Interface-Chatbot/ChatbotDrawer.tsx

turncate the subthread id

---

src/pages/interface/components/Interface-Chatbot/Message.tsx

updated preview image for vision main

updated preview image for vision main

---

src/api/InterfaceApis/InterfaceApis.ts
src/pages/interface/components/Interface-Chatbot/InterfaceChatbot.tsx
src/pages/interface/components/Interface-Chatbot/MessageList.tsx

starter question - testing

---

src/api/InterfaceApis/InterfaceApis.ts
src/pages/interface/components/Interface-Chatbot/InterfaceChatbot.tsx
src/pages/interface/components/Interface-Chatbot/MessageList.tsx

starter questions main

---

src/pages/interface/components/Interface-Chatbot/ChatbotDrawer.tsx

subthread bug solve

---

src/pages/interface/components/Interface-Chatbot/MessageList.tsx

desinged starter question

---

src/pages/interface/components/Interface-Chatbot/ChatbotDrawer.tsx
src/pages/interface/components/Interface-Chatbot/ChatbotHeader.tsx
src/pages/interface/components/Interface-Chatbot/InterfaceChatbot.tsx

set loading false on subthread change

set loading false on subthread change

---

src/pages/interface/components/Interface-Chatbot/ChatbotDrawer.tsx
src/pages/interface/components/Interface-Chatbot/ChatbotHeader.tsx
src/pages/interface/components/Interface-Chatbot/InterfaceChatbot.tsx

set laoding false on subthread change

set laoding false on subthread change

---

package-lock.json
package.json
src/pages/interface/components/Interface-Chatbot/InterfaceChatbot.tsx

subscribing after 500 ms- test

---

package-lock.json
package.json
src/pages/interface/components/Interface-Chatbot/InterfaceChatbot.tsx

Rt layer update test

---

src/App.js
src/api/InterfaceApis/InterfaceApis.ts
src/interceptor/interceptor.js
src/pages/rag/ragCompoonent.tsx

implement thrid party rag component

implement thrid party rag component
